apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example

spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example
          image: busybox
          command: ["sh", "-c"]
          args:
            - while true; do
              echo ${MY_POD_NAME} $(date);
              sleep 1;
              done;
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
